"""
Add or overwrite subblock composition arrays into the shared master HDF5 container,
using the existing splits generated by the main preprocessor.
"""

from __future__ import annotations
import h5py
import numpy as np
from pathlib import Path

# --- File Paths ---
PROCESSED_DIR = Path("./processed")
COMP_NPZ = PROCESSED_DIR / "subblock_compositions.npz"

# Target Shared HDF5 File (The same file the other preprocessor writes to)
OUT_H5 = PROCESSED_DIR / "antenna_data_4x4_subblock.h5"

# READ-ONLY Split Reference (Made by the main preprocessor script)
EXISTING_SUBBLOCK_SPLITS = PROCESSED_DIR / "split_indices_4x4_subblock.npz"

# Output Statistics for your specific subblock matrix
NORM_SUB = PROCESSED_DIR / "norm_stats_subblock_4x4.npz"


def load_raw_data() -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Loads and standardizes data from your original snippet."""
    print(f"Loading raw data from {COMP_NPZ}...", flush=True)
    if not COMP_NPZ.exists():
        raise FileNotFoundError(f"Missing source file: {COMP_NPZ}")
        
    comp = np.load(COMP_NPZ)
    n_all = len(comp["idx"])
    
    idx_1 = comp["idx"][:n_all].astype(np.int64)
    gi0 = idx_1 - 1
    
    sb4 = comp["sub_block_4x4"][:n_all].astype(np.float32)
    dpx_all = comp["dpx"][:n_all].astype(np.float32)
    dpy_all = comp["dpy"][:n_all].astype(np.float32)
    
    return gi0, sb4, dpx_all, dpy_all


def get_existing_train_indices(n_total: int) -> np.ndarray:
    """Reads the train indices and ensures they safely fit within the current array bounds."""
    if not EXISTING_SUBBLOCK_SPLITS.exists():
        raise FileNotFoundError(
            f"Missing required split file: {EXISTING_SUBBLOCK_SPLITS.name}."
        )
    
    print(f"Reading authoritative train split from {EXISTING_SUBBLOCK_SPLITS.name}...", flush=True)
    sp = np.load(EXISTING_SUBBLOCK_SPLITS)
    train_idx = sp["train"].astype(np.int64)
    
    # --- FIX 1: Handle 1-based indexing if detected ---
    # If the maximum index in the split file equals or exceeds n_total, 
    # but the minimum is 1, it's highly likely a 1-based index tracker.
    if train_idx.max() >= n_total and train_idx.min() > 0:
        print(" 💡 Detected 1-based indices in split file. Converting to 0-based layout...", flush=True)
        train_idx = train_idx - 1

    # --- FIX 2: Boundary Guard (Clip to valid array size) ---
    # Only keep indices that are strictly less than our total number of rows
    valid_mask = train_idx < n_total
    filtered_train_idx = train_idx[valid_mask]
    
    dropped = len(train_idx) - len(filtered_train_idx)
    if dropped > 0:
        print(f" ⚠️ Dropped {dropped} training indices that were out of bounds for array size {n_total}.", flush=True)
        
    return filtered_train_idx

def append_to_shared_hdf5(sb4: np.ndarray, gi0: np.ndarray) -> None:
    """Appends or overwrites subblock data directly within the existing master HDF5 file."""
    if not OUT_H5.exists():
        raise FileNotFoundError(
            f"Master file {OUT_H5} not found! "
            f"Please run the main preprocessor script first to establish the HDF5 baseline."
        )

    print(f"Opening shared HDF5 file in append mode: {OUT_H5.name}...", flush=True)
    n_total = len(sb4)
    spatial_shape = sb4.shape[1:]

    with h5py.File(OUT_H5, "r+") as f:
        # Check if the file's primary dimensions match your subblock row count
        # This acts as a sanity check to ensure your npz matches the H5 file length
        if "matlab_4x4" in f and f["matlab_4x4"].shape[0] != n_total:
            print(f"⚠️ Warning: HDF5 has {f['matlab_4x4'].shape[0]} samples, "
                  f"but your subblock data has {n_total} samples. Proceeding anyway.")
        
        # If 'subblock_4x4' dataset already exists, clean it up before replacing it
        if "subblock_4x4" in f:
            print(" -> Overwriting existing 'subblock_4x4' dataset...", flush=True)
            del f["subblock_4x4"]
        else:
            print(" -> Appending new 'subblock_4x4' dataset...", flush=True)

        f.create_dataset(
            "subblock_4x4",
            data=sb4.astype(np.float16),
            shape=(n_total, *spatial_shape),
            dtype=np.float16,
            chunks=(1, *spatial_shape),
            compression="gzip",
            compression_opts=4,
        )
        
        if "subblock_global_idx" in f:
            del f["subblock_global_idx"]
        f.create_dataset("subblock_global_idx", data=gi0, dtype=np.int64)

    print(f"Successfully updated master HDF5 storage ({OUT_H5.stat().st_size / 1e6:.1f} MB)", flush=True)


def compute_training_stats(sb4: np.ndarray, train_idx: np.ndarray) -> None:
    """Computes spatial mean/std filtered exclusively on the existing train set."""
    print("Computing normalization stats from shared training split...", flush=True)
    
    # Slice features matrix using the exact indices loaded from the main script's split file
    train_samples = sb4[train_idx]
    
    mean = train_samples.mean(axis=0).astype(np.float32)
    std = train_samples.std(axis=0).astype(np.float32)
    std = np.maximum(std, 1e-6)
    
    np.savez(NORM_SUB, mean=mean, std=std)
    print(f"Wrote stats to {NORM_SUB.name}", flush=True)


def main() -> None:
    # 1. Load your raw numpy data arrays
    gi0, sb4, dpx_all, dpy_all = load_raw_data()
    n_total = len(gi0) # e.g., 1000
    
    # 2. Read the existing splits (Safeguarded against index out-of-bounds!)
    train_idx = get_existing_train_indices(n_total)
    
    # 3. Inject your data into the main H5 file alongside everything else
    append_to_shared_hdf5(sb4, gi0)
    
    # 4. Calculate stats purely based on that official training split
    compute_training_stats(sb4, train_idx)
    
    print("\nData merged successfully with zero modifications to existing split files!", flush=True)

if __name__ == "__main__":
    main()